//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWeb.Mobile.UserControls
{
    public partial class BillingForm
    {

        protected global::System.Web.UI.WebControls.TextBox txtFirstName, txtEmail, txtLastName, txtAddress1, txtCity,
        txtAddress2, txtZipCode, txtArea, txtPhoneNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlCountry, ddlState, ddlQuantityList;
        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonItemSelect;
        protected global::System.Web.UI.WebControls.Literal IDLiteral;
        protected global::System.Web.UI.WebControls.Label lblStateError, lblZiPError, lblFirstNameError, lblLastNameError, lblAddress1Error,
            lblPhoneNumberError, lblEmailError, lblCityError, lblQuantityList;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName, rfvLastName, rfvAddress1, rfvCity, rfvZipCode, rfvPhoneNumber, rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;  
    }
}
